### ISSUE TITLE
Positive and negative button text are mixed

### ISSUE THREAD

**Issue by SirSebaa** [RamonRemo/timer_picker#1]
The properties to change the positive and negative button text are mixed, in the buildPositiveButton() you set the negativeButtonText property and in the buildNegativeButton() you set the positiveButtonText property. And you are not using the positiveButtonStyle, just the negativeButtonStyle in both buttons.

![image](https://user-images.githubusercontent.com/47335829/158236836-d8e92bed-9373-40ad-b0de-7b0fd029dbc7.png)

![image](https://user-images.githubusercontent.com/47335829/158236926-919d4405-487c-430f-a47e-6c985a90139b.png)

**Comment by RamonRemo** [comment]
Fixed!
thanks for notice.
